# Generated by Django 4.2.2 on 2023-06-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0003_class_class_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="date",
        ),
        migrations.AddField(
            model_name="class",
            name="day",
            field=models.CharField(
                choices=[
                    ("MO", "Monday"),
                    ("TU", "Tuesday"),
                    ("WE", "Wednesday"),
                    ("TH", "Thursday"),
                    ("FR", "Friday"),
                    ("SA", "Saturday"),
                    ("SU", "Sunday"),
                ],
                default="Monday",
                max_length=16,
            ),
        ),
    ]
