# Generated by Django 4.2.2 on 2023-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0004_remove_class_date_class_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.TimeField(),
        ),
    ]
