# Generated by Django 4.2.2 on 2023-06-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0005_alter_class_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="day",
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
