# Generated by Django 4.2.2 on 2023-06-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0006_remove_class_day_alter_class_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(default="2023-08-14 18:00:00"),
        ),
    ]
