# Generated by Django 4.2.2 on 2023-06-13 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0007_alter_class_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"ordering": ["time"]},
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 13, 11, 11, 13, 282116)
            ),
        ),
    ]
