# Generated by Django 4.2.2 on 2023-06-16 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0012_studio_location_alter_class_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 16, 12, 52, 25, 317598)
            ),
        ),
    ]
