# Generated by Django 4.2.2 on 2023-06-16 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0013_alter_class_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studio",
            name="location",
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 16, 13, 4, 23, 166359)
            ),
        ),
    ]
