# Generated by Django 4.2.2 on 2023-06-25 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0019_alter_class_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studio",
            old_name="name",
            new_name="studio_name",
        ),
        migrations.AddField(
            model_name="studio",
            name="owner_fr_name",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="studio",
            name="owner_lt_name",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 25, 15, 58, 1, 325222)
            ),
        ),
    ]
