# Generated by Django 4.2.2 on 2023-09-21 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0021_alter_class_time_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 21, 13, 47, 39, 513272)
            ),
        ),
    ]
