# Generated by Django 4.2.2 on 2023-10-03 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0024_class_price_user_credits_alter_class_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 3, 13, 27, 47, 991117)
            ),
        ),
    ]
