# Generated by Django 4.2.2 on 2023-10-03 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0029_alter_class_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="fives",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 3, 14, 18, 22, 966449)
            ),
        ),
    ]
