# Generated by Django 4.2.2 on 2023-10-03 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0031_class_rating2_alter_class_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="fives",
        ),
        migrations.RemoveField(
            model_name="class",
            name="rat_amount",
        ),
        migrations.RemoveField(
            model_name="class",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="class",
            name="rating2",
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 3, 14, 41, 13, 115719)
            ),
        ),
    ]
