# Generated by Django 4.2.2 on 2023-10-08 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0032_remove_class_fives_remove_class_rat_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studio",
            old_name="city",
            new_name="studio_city",
        ),
        migrations.RemoveField(
            model_name="studio",
            name="classes",
        ),
        migrations.RemoveField(
            model_name="studio",
            name="reviews",
        ),
        migrations.AddField(
            model_name="studio",
            name="studio_classes",
            field=models.ManyToManyField(
                blank=True, default="", related_name="studio_classes", to="sport.class"
            ),
        ),
        migrations.AddField(
            model_name="studio",
            name="studio_reviews",
            field=models.ManyToManyField(
                blank=True, default="", related_name="studio_reviews", to="sport.review"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 8, 8, 24, 41, 881198)
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="address",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="studio",
            name="studio_name",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="studio",
            name="trainers",
            field=models.ManyToManyField(
                blank=True,
                default="",
                related_name="studio_trainers",
                to="sport.trainer",
            ),
        ),
    ]
