# Generated by Django 4.2.2 on 2023-10-08 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0033_rename_city_studio_studio_city_remove_studio_classes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 8, 15, 3, 47, 304626)
            ),
        ),
    ]
