# Generated by Django 4.2.2 on 2023-10-08 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0034_alter_class_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="studio_owner",
            field=models.BooleanField(default="False"),
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 8, 15, 7, 23, 607257)
            ),
        ),
    ]
