# Generated by Django 4.2.2 on 2023-10-08 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0036_alter_class_time_studio_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="credits",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 8, 16, 20, 32, 433853)
            ),
        ),
    ]
