# Generated by Django 4.2.2 on 2023-10-08 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0037_studio_credits_alter_class_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 8, 16, 21, 16, 611011)
            ),
        ),
    ]
