# Generated by Django 4.2.2 on 2023-10-09 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0038_alter_class_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan",
            field=models.CharField(
                choices=[
                    ("9", "9 credits/mo"),
                    ("25", "25 credits/mo"),
                    ("47", "47 credits/mo"),
                    ("64", "64 credits/mo"),
                    ("80", "80 credits/mo"),
                ],
                default="47 credits/mo",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 9, 10, 36, 40, 905560)
            ),
        ),
    ]
