# Generated by Django 4.2.2 on 2023-10-16 12:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport", "0039_user_plan_alter_class_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="class_signed_up_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 16, 12, 25, 34, 856326)
            ),
        ),
    ]
